name: 'foundry-toolchain'
description: 'Install Foundry'
author: 'Oliver Nordbjerg'
branding:
  icon: play-circle
  color: gray-dark
inputs:
  version:
    description: |
      Foundry version.

      This version number has to match a released version of Foundry.
      Alternatively you can also specify `nightly` for the latest nightly build.

runs:
  using: node16
  main: dist/index.js
